name: Building new Clang

on:
  push:
    branches:
      - clang/main
  schedule:
    - cron: '15 0 * * *'

env:
  GIT_SECRET: ${{ secrets.GIT_SECRET }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  EmpatLebas:

    runs-on: ubuntu-latest

    container:
      image: zycromerz/tcdocker:v1

    steps:
    - uses: actions/checkout@v2
    - name: Build TC 14
      run: |
        export DEBIAN_FRONTEND=noninteractive
        export PATH=/usr/bin/core_perl:$PATH
        cp -af kernel/build-mod.sh kernel/build.sh
        bash ci.sh deps
        bash clang-builder.sh 14 gi

  MainAja:

    runs-on: ubuntu-latest

    container:
      image: zycromerz/tcdocker:v1

    steps:
    - uses: actions/checkout@v2
    - name: Build TC Main
      run: |
        export DEBIAN_FRONTEND=noninteractive
        export PATH=/usr/bin/core_perl:$PATH
        cp -af kernel/build-mod.sh kernel/build.sh
        bash ci.sh deps
        bash clang-builder.sh main gi
