name: Building new Clang

on:
  push:
    branches:
      - clang/main
  schedule:
    - cron: '15 0 * * *'

env:
  GITLAB_NAME: ${{ secrets.GITLAB_NAME }}
  GITLAB_SECRET: ${{ secrets.GITLAB_SECRET }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  GIT_SECRET: ${{ secrets.GIT_SECRET }}

jobs:
  
  MainAja:

    runs-on: ubuntu-20.04

    container:
      image: zycromerz/tcdocker:v1

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: clang-main

    - name: Build TC main
      run: |
        cd clang-main
        export DEBIAN_FRONTEND=noninteractive
        export PATH=/usr/bin/core_perl:$PATH
        bash ci.sh deps
        bash update-clang-version.sh main
        bash clang-builder.sh main gi
